### PR TITLE
Add a re-frame friendly version of forms.core

### PR DESCRIPTION
**Pull request by mynomoto**
This uses the re-frame state instead of the Protocol/Record. I had trouble with changes not propagating putting the Record on re-frame db and wanted something more re-frame friendly.

Please let me know if this is wanted or not, thanks!

### CODE REVIEW

**Comment by retro** [comment]
@mynomoto Hi, thank you for your pull request. My only concern is that this library now depends on re-frame instead of reagent. I'm not using re-frame in my apps, so I would check if we can make it so that re-frame is used only in test context. I would expect users to provide their version of re-frame anyway

**Comment by mynomoto** [comment]
@retro I will test it. Is it ok that I updated the dependencies/plugins and should I do the same for `reagent`?

**Comment by retro** [comment]
Updating deps is great, thanks. I'll check this tomorrow and merge.

Thank you again.

**Comment by mynomoto** [comment]
Let me know if there are more changes that you would like me to do. I also added a PR to add an example on https://github.com/keechma/example-forms/pull/2

**Comment by retro** [comment]
@mynomoto v0.1.4 is out with your changes merged in. Thank you for your contribution!

**Pull request merged**
